### ISSUE TITLE
Can't create a button controller

### ISSUE THREAD

**Issue by JiaChen-Zeng** [domportera/Reaper-LAN-OSC-MIDI-Faders-Android#4]
When clicking new controller button and selecting a controller type, I can't select "Button" type. Nothing happens when I click "Button". For "From Template" it's the same.

**Comment by domportera** [comment]
hey! I see you made a build (sorry for the late reply i didnt see this)
yes that functionality is not implemented - it was there as a placeholder. I have since removed it. I would like to support these features, but atm im just trying to get a stable build out

just wondering, as you were using this - it was working well for you? are there any other hiccups you hit along the way?

**Comment by JiaChen-Zeng** [comment]
Hi, thank you for the explanation.

It is working great. I haven't used extensively but so far no other
problems.
A quick update on the go.
移動中に取り急ぎご連絡まで。

**Comment by domportera** [comment]
great to hear!! thanks :)

**Comment by domportera** [comment]
closing due to the nature of the issue - if someone wants to create a feature request for these things, dont let this closed issue stop you
